In [1]:
import pandas as pd

w = pd.read_csv("weibull_online_monthly.csv")
w["date"] = pd.to_datetime(w["date"])
w = w.set_index("date")
w.head()

                     residual  prediction
date
2018-07-03 23:00:00 -0.000102    0.000183
2018-07-04 00:00:00  0.000105    0.000345
2018-07-04 01:00:00  0.000039    0.000279
2018-07-04 02:00:00  0.000115    0.000287
2018-07-04 03:00:00  0.000061    0.000238

In [2]:
true = pd.read_csv("data/btc/data_df.csv")
true["datetime"] = pd.to_datetime(true["datetime"])
true = true.set_index("datetime")
true = true["vol"]
true.head()

datetime
2018-06-04 23:00:00    0.000143
2018-06-05 00:00:00    0.000115
2018-06-05 01:00:00    0.000090
2018-06-05 02:00:00    0.000502
2018-06-05 03:00:00    0.000146
Name: vol, dtype: float64

In [28]:
m = pd.read_csv("output_retrain.csv")
m["datetime"] = pd.to_datetime(m["datetime"])
m = m.set_index("datetime")
m

,retraining_flag,model_name,MLPPredictor,LSTMSoftplusPredictor,TransformerPredictor,SigmaLSTMPredictor
datetime,,,,,,
2018-07-03 23:00:00,True,NaN,2.156055,0.000057,0.000058,0.017133
2018-07-04 00:00:00,False,NaN,1.566001,0.000057,0.000059,0.010147
2018-07-04 01:00:00,False,NaN,1.877611,0.000057,0.000059,0.004732
2018-07-04 02:00:00,False,NaN,1.906388,0.000057,0.000059,0.005149
2018-07-04 03:00:00,False,NaN,1.846373,0.000057,0.000059,0.000219
...,...,...,...,...,...,...
2018-09-30 17:00:00,False,NaN,NaN,NaN,NaN,NaN
2018-09-30 18:00:00,False,NaN,NaN,NaN,NaN,NaN
2018-09-30 19:00:00,False,NaN,NaN,NaN,NaN,NaN
2018-09-30 20:00:00,False,NaN,NaN,NaN,NaN,NaN
2018-09-30 21:00:00,False,NaN,NaN,NaN,NaN,NaN

In [29]:
d = m.merge(w, left_index=True, right_index=True, how="left")
d = d.merge(true, left_index=True, right_index=True, how="left")
d.shape

(1958, 9)

In [31]:
d = d.dropna(subset=["vol", "SigmaLSTMPredictor"])
d

,retraining_flag,model_name,MLPPredictor,LSTMSoftplusPredictor,TransformerPredictor,SigmaLSTMPredictor,residual,prediction,vol
datetime,,,,,,,,,
2018-07-03 23:00:00,True,NaN,2.156055,0.000057,0.000058,0.017133,-0.000102,0.000183,0.000285
2018-07-04 00:00:00,False,NaN,1.566001,0.000057,0.000059,0.010147,0.000105,0.000345,0.000241
2018-07-04 01:00:00,False,NaN,1.877611,0.000057,0.000059,0.004732,0.000039,0.000279,0.000240
2018-07-04 02:00:00,False,NaN,1.906388,0.000057,0.000059,0.005149,0.000115,0.000287,0.000173
2018-07-04 03:00:00,False,NaN,1.846373,0.000057,0.000059,0.000219,0.000061,0.000238,0.000177
...,...,...,...,...,...,...,...,...,...
2018-09-26 18:00:00,False,NaN,0.018549,0.000057,0.000054,0.000488,0.000066,0.000078,0.000012
2018-09-26 19:00:00,False,NaN,0.016425,0.000057,0.000054,0.007757,0.000027,0.000045,0.000018
2018-09-26 20:00:00,False,NaN,0.016879,0.000057,0.000054,0.000006,0.000031,0.000036,0.000006
2018-09-26 21:00:00,False,NaN,0.014793,0.000057,0.000054,0.000132,-0.000009,0.000047,0.000056
2018-09-26 22:00:00,False,NaN,0.014103,0.000057,0.000054,0.002124,-0.000025,0.000047,0.000072

In [34]:
from sklearn.metrics import root_mean_squared_error

root_mean_squared_error(d["vol"], d["LSTMSoftplusPredictor"])

0.00025452908179836943